package com.whiteteal.quizappfirebase.URL_Constants;

/**
 * Created by gayatri on 18/4/17.
 */
public interface StausCodes {
    //response codes
    String RESPONSE_INTERNALSERVER_ERROR = "500";
    String RESPONSE_ACCESSTOKEN_MISSING = "400";
    String RESPONSE_ACCESSTOKEN_EXPIRED = "401";
    String RESPONSE_INVALID_ACCESSTOKEN = "402";
    String RESPONSE_SUCCESS = "200";

    //status codes
    String STATUSCODE_SUCCESS="201";
    String STATUS_ERROR_OCCURED="202";
    String STATUSCODE_MISSING_PARAMETER="203";
    String STATUSCODE_ALREADYREGISTERED="204";
    String STATUSCODE_GRNO_NOTVALID="205";
    String STATUSCODE_REG_SUCC_EMAILNOTLINKED="206";
    String STATUSCODE_INVALIDUSERNAMEORPASWD="207";
    String STATUSCODE_PASSWORD_MISMATCH="208";
    String STATUSCODE_INVALIDUSER="209";
    String STATUSCODE_OTPSEND="210";
    String STATUSCODE_ALLREADYEXISTS="211";
    String STATUS_CODE_PAGE_NOTFOUND="212";
    String STATUS_CODE_INVALID_OTP="213";
    String STATUS_CODE_NO_QUIZ="215";
    String STATUS_CODE_RENEW_TOKEN="216";
}
